---
title: "SVM"
author: '35642114'
date: "2025-05-08"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
```

```{r}
library(ggpubr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tidyr)
library(dplyr)
library(tidymodels)
library(glmnet)
library(janitor)
library(patchwork)
library(fairml)
library(tibble)
library(discrim)
library(rpart.plot)
library(rpart)
library(vip)
library(yardstick)
library(broom)

r2oos <- function(d, var) {
 rmse <- d |> rmse({{var}}, .pred) |> pull(.estimate) 
# mse <- rmse(d, var, .pred)$.estimate^2
 riv <- d |> rmse({{var}}, .pred_c) |> pull(.estimate)
# iv <- rmse(d, var, .pred_c)$.estimate^2 
 1 - (rmse * rmse) / (riv * riv)
}
svr_results_path<-"C:/Users/xh2u24/Desktop/p4-INLASPDE/results-R-svr"
```

```{r}
svr_results_path<-"C:/Users/xh2u24/Desktop/p4-INLASPDE/results-R-svr"
```

# ##svm_rbf
```{r}
#| label: svm_rbf -specification
set.seed(35642114)

svm_spec <- svm_rbf(cost=NULL, rbf_sigma=NULL, margin=NULL) |>
 set_mode("regression") |>
  set_engine("kernlab")

svm_wflow <- workflow() |>
  add_recipe(q2_recipe) |>
  add_model(svm_spec)

 svm_q2_fit <- fit(svm_wflow, q2_train)

q2_pred <- svm_q2_fit |>
  augment(q2_test) |>
  mutate(.pred_c = mean(q2_train$resp))

rmse(q2_pred, resp, .pred)
rsq (q2_pred, resp, .pred)
r2oos(q2_pred, resp)

svm_all_fit <- fit(svm_wflow, q2_data)
###VI
visp.svr<-vip(
  extract_fit_parsnip(svm_all_fit ),# extract model
  feature_names = names(q2_data%>% select(-resp)) ,
  method = "permute",
  train = q2_test,#data.frame
  target = "resp",# vector
  pred_wrapper = function(object, newdata) {
    as.vector(predict(object, newdata)) },# object:extract model; newdata:train
  metric = "rsq",
  keep = T,
   num_features = 8,
  geom = "point",
  nsim = 20# permute 30 times to stablize the outcome
)
visp.svr

ggsave(filename=paste0(svr_results_path, "/feature/VI.png"), plot = visp.svr, width = 6, height = 4, dpi = 300)
write.csv(visp.svr$data, file=paste0(svr_results_path, "/feature/VI.csv"))
```

```{r}
#| label: tuning-setup
# using all available cores

set.seed(35642114)

svm_tune_spec <- svm_rbf(cost=tune(), rbf_sigma=tune()) |>
  set_mode("regression") |>
  set_engine("kernlab")

svm_tune_wflow <- workflow() |>
  add_recipe(q2_recipe) |>
  add_model(svm_tune_spec)
```

# ################################Bayesian optimization
```{r}
#| label: Bayesian Opt
plan(multisession, workers =20)

start_time <- Sys.time()

library(ggplot2)
library(finetune)
library(glue)

svm_param <- parameters(cost(), rbf_sigma()) %>%
  update(
    cost = cost(range = log10(c(1, 8)), trans=log10_trans()),
    rbf_sigma = rbf_sigma(range = log10(c(0.005, 0.03)), trans=log10_trans()) # 10^-3---10^-1
    )

folds <- vfold_cv(q2_train, v = 5)

bayes_svm <- tune_bayes(
  svm_tune_wflow,
  resamples = folds,
  initial = 20  ,
  iter = 50,  
  param_info = svm_param,     
  metrics = metric_set(rmse, rsq),
  control = control_bayes(verbose = TRUE)
)

metric<-show_best(bayes_svm, metric = "rsq")
autoplot1<-autoplot(bayes_svm, metric = "rsq") + theme_bw()
autoplot2<-autoplot(bayes_svm, metric = "rsq") +
  scale_x_continuous(
    labels = function(x) round(10^x, 3), 
    name = "Cost (original scale)"
  ) +
  theme_bw()

autoplot<-ggarrange(autoplot1,autoplot2,
          nrow = 2, ncol = 1)

ggsave(filename=paste0(svr_results_path, "/feature/autoplot.png"), plot = autoplot, width = 6, height = 6, dpi = 300)
write.csv(metric, file=paste0(svr_results_path, "/feature/metric.csv"))


default_plan <- plan()
plan(sequential)
```

```{r}
#| label:  Retraining with the optimal hyperparameters combination  + VI
plan(multisession, workers =20)
set.seed(35642114)
BO_svm <- select_best(bayes_svm, metric = "rsq")

final_svm_fit <- svm_tune_wflow |>
 finalize_workflow(BO_svm) |>
 last_fit(q2_split)#train on the train_data,test on the test_data

collect_metrics(final_svm_fit)  # for last_fit()

###VI
visp.svr<-vip(
  extract_fit_parsnip(final_svm_fit ),# extract model
  feature_names = names(q2_data%>% select(-resp)) ,
  method = "permute",
  train = q2_test,#data.frame
  target = "resp",# vector
  pred_wrapper = function(object, newdata) {
    as.vector(predict(object, newdata)) },# object:extract model; newdata:train
  metric = "rsq",
  keep = T,
   num_features = 8,
  geom = "point",
  nsim = 20# permute 30 times to stablize the outcome
)
visp.svr

ggsave(filename=paste0(svr_results_path, "/feature/VI.png"), plot = visp.svr, width = 6, height = 4, dpi = 300)
write.csv(visp.svr$data, file=paste0(svr_results_path, "/feature/VI.csv"))

# Restore the default
plan(sequential)
```





















